### PR TITLE
Setup travis build.

### PR DESCRIPTION
**Pull request by tmcgilchrist**

### CODE REVIEW

**Comment by tmcgilchrist** [comment]
@afcowie @luke-clifton 

Will need to setup builds in travis website for this change to trigger builds.

**Comment by luke-clifton** [comment]
Could you also chat with@lancelet and @mjhopkins about which stack version
they are using?

**Comment by afcowie** [comment]
fwiw I just use whatever is merged in master. I probably shouldn't! but **stack** has always been good to me that way.

**Comment by luke-clifton** [comment]
Sorry, I meant which stackage snapshot/lts release, not which version of the binary.

**Comment by mjhopkins** [comment]
Stack 1.6.3 
I think it was avoiding the 

```
"Error in $.packages.cassava.constraints.flags['bytestring--lt-0_10_4']: Invalid flag name: \"bytestring--lt-0_10_4\""
```

that necessitated the upgrade from 1.5.x.

LTS-10.3/

**Pull request merged**
