### PR TITLE
Setup external dependencies as git submodules.

### PR DESCRIPTION
**Pull request by tmcgilchrist**
Right now monad-bayes isn't released onto hackage. Once it is we can use that version.

@afcowie

### CODE REVIEW

**Comment by tmcgilchrist** [comment]
Actually this isn't right the `MonadSample` type class that used to exist doesn't anymore.
There may be a release to hackage soon [1] so it would be great if it either worked from that.

[1] https://github.com/adscib/monad-bayes/issues/41

**Comment by tmcgilchrist** [comment]
@luke-clifton

**Comment by luke-clifton** [comment]
We are using the `simple` branch from monad-bayes which I believe is the one that will be released. MonadSample is in there. That project is in flux, hence why we are currently pinned to a specific SHA. Can you arrange for the submodule to do the same?

Please drop the package constraints from the cabal file, we are using stackage for this. If you'd like to discuss it, raise a seperate PR.

**Comment by afcowie** [comment]
I was going to suggest that rather than using a git submodule, consider using _stack.yaml_; but by the time I got here you'd closed this already. Since we're discussing it, thought, is there a material difference between:

```text
packages:
- .
- location: https://github.com/luke-clifton/monad-bayes/archive/4227c548abc477247a7e3cee932a49c6bdfe29f9.zip
```
that @luke-clifton has in _stack.yaml_ now, and say

```
extra-deps:
- git: git@github.com:luke-clifton/monad-bayes.git
  commit: 4227c548abc477247a7e3cee932a49c6bdfe29f9
```
or so?

The apparent answer is the difference between `package` and `extra-deps`, see https://docs.haskellstack.org/en/stable/yaml_configuration/#packages-and-extra-deps for discussion (seems to be loaded into GHCi vs treated as a build dependency?)

[and then my question for @tmcgilchrist is whether that's suitable for the constraint you were looking for, or whether using submodules (or...) would have had a different benefit.]

AfC

_so many years ago they put the fear of god into me about submodules, but perhaps that's baggage that is no longer relevant_

**Comment by luke-clifton** [comment]
On 8 February 2018 at 19:42, Andrew Cowie <notifications@github.com> wrote:

> is there a material difference between:
>
> packages:
> - .
> - location: https://github.com/luke-clifton/monad-bayes/archive/4227c548abc477247a7e3cee932a49c6bdfe29f9.zip
>
> that @luke-clifton <https://github.com/luke-clifton> has in *stack.yaml*
> now, and say
>
> extra-deps:
> - git: git@github.com:luke-clifton/monad-bayes.git
>   commit: 4227c548abc477247a7e3cee932a49c6bdfe29f9
>
>
No. If you have a look again, my config has `extra-dep: true`  on that
package, which makes it behave exactly like an `extra-dep` that you are
suggesting. The only difference is the syntax you propose is a relatively
new feature (see [this writeup for details](
https://www.fpcomplete.com/blog/2017/07/stacks-new-extensible-snapshots)).
We could change to this syntax at no cost.

The other difference is that I am using a tarball (ok, zip) download, which
improves performance over going to `git` directly.


> [and then my question for @tmcgilchrist <https://github.com/tmcgilchrist>
> is whether that's suitable for the constraint you were looking for, or
> whether using submodules (or...) would have had a different benefit.]


From the looks of things @tmcgilchrist wants to use raw `cabal` (a position
I completely understand :smile:), so no amount of stack config will work.


> *so many years ago they put the fear of god into me about submodules, but
> perhaps that's baggage that is no longer relevant*
>
I have this same fear, but can't really articulate why, other than perhaps
git hating me. If it improves someones workflow, I'm happy to do it.

**Comment by tmcgilchrist** [comment]
I closed this PR cause I was working under false assumptions around tooling and the status of 
depdencies so it's probably better to drop this as a PR.

The monad-bayes people sounded like they were close to having a hackage release, which would 
be good to make sure we are compatible with. The git submodule things was an attempt to set 
that up in a way I typically work. Happy to discuss this workflow, perhaps to a wider audience 
via another channel.

@luke-clifton yes I would very much support a position that is compatible with cabal and the wider 
haskell ecosystem. See internal PR.

**Pull request closed without merging**
